name: CI/CD Pipeline

on: [push]

jobs:    
  run-backend-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
        
    - name: Install dependencies for backend
      run: npm ci --prefix gis-desktop-backend
    
    - name: Install dependencies for frontend
      run: npm ci --prefix frontend-electron
    
    #- name: Start backend server
    #  run: npm start --prefix gis-desktop-backend
    
  electron-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-electron

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
        
    - name: Install dependencies
      run: npm ci --prefix frontend-electron
    
    #- name: E2E Test for Electron
    #  run: npm run ui-test --prefix frontend-electron

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: tests/screenshots/**
